# Generated by Django 4.2.2 on 2023-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employer_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('company_link', models.CharField(max_length=30)),
            ],
        ),
    ]
