# Generated by Django 4.2.2 on 2023-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydescription',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
