# Generated by Django 4.2.2 on 2023-07-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_companydescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydescription',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='main.employer'),
        ),
    ]
