# Generated by Django 4.2.2 on 2023-07-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_companydescription_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDescription',
        ),
    ]
