# Generated by Django 4.2.2 on 2023-08-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_companydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], null=True),
        ),
    ]
